# version: '3'
# services:
#   redis:
#     image: redis
#     ports:
#       - "6379:6379"
#     networks:
#       - mynetwork

#   mysql:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: DB_ACESSO
#       MYSQL_ROOT_HOST: '%'
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./mysql_data:/var/lib/mysql
#     networks:
#       - mynetwork
#     init_db_script: /docker-entrypoint-initdb.d/init.sql

#   data_receiver:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - redis
#       - mysql
#     networks:
#       - mynetwork

# networks:
#   mynetwork:
#     driver: bridge

version: '3.8'

services:
  mysql:
    image: mysql:8.0.25
    container_name: MYSQL
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_ACESSO
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2-alpine
    container_name: REDIS
    command: redis-server --requirepass Redis2019!
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

volumes:
  cache:
    driver: local